version: '3.8'
services:

  frontend:
    build: .
    ports:
      - "8080:3000"
    volumes:
      - ./app:/app/app
      - ./nuxt.config.ts:/app/nuxt.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./public:/app/public
    environment:
      NITRO_PORT: 3000
      NUXT_STRAPI_URL: http://strapi:1337/api
      NUXT_PUBLIC_STRAPI_URL: http://localhost:1337/api
    depends_on:
      - strapi
    networks:
      - app-network

  strapi:
    build:
      context: ./BallzzyDspCMS
      dockerfile: Dockerfile
    env_file:
      - ./BallzzyDspCMS/.env
    ports:
      - "1337:1337"
    restart: always
    volumes:
      - ./BallzzyDspCMS/src:/opt/app/src     
      - ./BallzzyDspCMS/public:/opt/app/public 
      - ./BallzzyDspCMS/data:/opt/app/data  

    depends_on:
      postgres:
        condition: service_healthy   # wait for postgres to be ready
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres        # service name = hostname in Docker network
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: false
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # named volume = persists across rebuilds
    ports:
      - "5432:5432"   # optional: expose if you want to inspect with a local DB client
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strapi -d strapi"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

networks:
  app-network:
    driver: bridge